olist_data_pipeline:
  outputs:
    dev:
      dataset: olist_dwh
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/balkis/Downloads/olist-assignment-497915-68366c85f98f.json
      location: US
      method: service-account
      priority: interactive
      project: olist-assignment-497915
      threads: 4
      type: bigquery
  target: dev